### ISSUE TITLE
How do you change the size.

### ISSUE THREAD

**Issue by bmrscott** [konpa/devicon#15]
how do you change the size of the HTML icon or do I have to use a SVG?

<i class="devicon-amazonwebservices-original"></i>

**Comment by konpa** [comment]
You simply use the font-size property in your stylesheet

HTML
```` HTML
<i class="devicon-git-plain"></i>
````

CSS
```` CSS
.devicon-git-plain {
  font-size: 2rem
}
````
